version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile_TurboRepo
    container_name: URL-shortener-FastAPI-backend
    ports:
      - "8000:8000"
    env_file:
      - apps/backend/.env

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: URL-shortener-NextJS-frontend
    ports:
      - "3000:3000"

